//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEventos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppEventos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navidad, 25/12/2019
        ///Hoy hace un año, 26/12/2018
        ///31, 31/12/2019
        ///Hoy a las 4:30pm, 15/1/2020 04:30 pm
        ///Hoy a las 1:49:25pm, 15/1/2020 1:49:25 pm
        ///Inicio del Curso Patrones de Diseño, 26/12/2019 8:30 am
        ///Año nuevo, 01/01/2020
        ///Día de la madre, 10/05/2019 
        ///.
        /// </summary>
        internal static string archivo {
            get {
                return ResourceManager.GetString("archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  día(s).
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hora(s).
        /// </summary>
        internal static string horas {
            get {
                return ResourceManager.GetString("horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mes(es).
        /// </summary>
        internal static string meses {
            get {
                return ResourceManager.GetString("meses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minuto(s).
        /// </summary>
        internal static string minutos {
            get {
                return ResourceManager.GetString("minutos", resourceCulture);
            }
        }
    }
}
